# Generated by Django 4.2.4 on 2023-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
